SELECT DISTINCT 
 
	   X.RA,X.NOMEALUNO,X.EMAIL
	   
	
FROM (SELECT STURMADISC.CODCOLIGADA CODCOLIGADA,
             STURMADISC.CODFILIAL CODFILIAL,
			 GFILIAL.NOMEFANTASIA NOMEFILIAL,
			 STIPOCURSO.CODTIPOCURSO CODNIVEL,
             STIPOCURSO.NOME NIVEL_ENSINO,
			 SCURSO.CODCURSO CODCURSO,
			 SCURSO.NOME CURSO,
			 SPLETIVO.CODPERLET PERIODO,
			 SDISCIPLINA.CODDISC CODDISC,
			 SDISCIPLINA.NOME DISCIPLINA,
			 STURMADISC.IDTURMADISC IDTURMA,
			 SALUNO.RA RA,
			 PPESSOA.NOME NOMEALUNO,
			 PPESSOA.EMAIL EMAIL

FROM STURMADISC (NOLOCK)
	INNER JOIN SPLETIVO				(NOLOCK) ON STURMADISC.CODCOLIGADA=SPLETIVO.CODCOLIGADA AND SPLETIVO.IDPERLET=STURMADISC.IDPERLET
	INNER JOIN SDISCIPLINA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SDISCIPLINA.CODCOLIGADA AND STURMADISC.CODDISC=SDISCIPLINA.CODDISC
	INNER JOIN SMATRICULA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SMATRICULA.IDTURMADISC
	INNER JOIN SSTATUS				(NOLOCK) ON SSTATUS.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SSTATUS.CODSTATUS=SMATRICULA.CODSTATUS
	INNER JOIN SMATRICPL			(NOLOCK) ON SMATRICPL.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SMATRICPL.RA=SMATRICULA.RA AND SMATRICPL.IDPERLET=SMATRICULA.IDPERLET 
												AND SMATRICPL.IDHABILITACAOFILIAL=SMATRICULA.IDHABILITACAOFILIAL
	INNER JOIN SFILIAL				(NOLOCK) ON SFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SFILIAL.CODFILIAL=SMATRICPL.CODFILIAL
	INNER JOIN GFILIAL				(NOLOCK) ON SFILIAL.CODCOLIGADA = GFILIAL.CODCOLIGADA AND SFILIAL.CODFILIAL=GFILIAL.CODFILIAL
	INNER JOIN SSTATUS STATUSLETIVO (NOLOCK) ON SMATRICPL.CODCOLIGADA = STATUSLETIVO.CODCOLIGADA AND SMATRICPL.CODSTATUS = STATUSLETIVO.CODSTATUS
	INNER JOIN SALUNO				(NOLOCK) ON SALUNO.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SALUNO.RA=SMATRICPL.RA
	INNER JOIN PPESSOA				(NOLOCK) ON PPESSOA.CODIGO=SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL	(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL=SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO				(NOLOCK) ON SCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STIPOCURSO			(NOLOCK) ON STIPOCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND STIPOCURSO.CODTIPOCURSO=SHABILITACAOFILIAL.CODTIPOCURSO


WHERE ( STIPOCURSO.NOME LIKE 'GRAD%' AND STURMADISC.TIPO = 'P' )
		AND NOT (SMATRICULA.CODCOLIGADA = 3 AND SHABILITACAOFILIAL.CODTIPOCURSO = 1)
		AND STURMADISC.CODFILIAL != 4
		AND SPLETIVO.CODPERLET IN ('2023/1')
		AND (UPPER(SSTATUS.DESCRICAO) LIKE 'MATRIC%' )
		

	GROUP BY STURMADISC.CODCOLIGADA,STURMADISC.CODFILIAL,GFILIAL.NOMEFANTASIA ,STIPOCURSO.CODTIPOCURSO, SCURSO.NOME, STIPOCURSO.NOME,SCURSO.CODCURSO,
	SCURSO.NOME,SPLETIVO.CODPERLET,SDISCIPLINA.CODDISC,SDISCIPLINA.NOME, STURMADISC.IDTURMADISC,SALUNO.RA,PPESSOA.NOME,PPESSOA.EMAIL
	
UNION

SELECT STURMADISC.CODCOLIGADA COLIGADA,
       STURMADISC.CODFILIAL CODFILIAL,
	   GFILIAL.NOMEFANTASIA NOMEFILIAL,
	   STIPOCURSO.CODTIPOCURSO CODNIVEL,
       STIPOCURSO.NOME NIVEL_ENSINO,
	   SCURSO.CODCURSO CODCURSO,
	   SCURSO.NOME CURSO,
	   SPLETIVO.CODPERLET PERIODO,
	   SDISCIPLINA.CODDISC CODDISC,
	   SDISCIPLINA.NOME DISCIPLINA,
	   STURMADISC.IDTURMADISC IDTURMA,
	   SALUNO.RA RA,
	   PPESSOA.NOME NOMEALUNO,
	   PPESSOA.EMAIL EMAIL

FROM STURMADISC (NOLOCK)
	INNER JOIN SPLETIVO				(NOLOCK) ON STURMADISC.CODCOLIGADA=SPLETIVO.CODCOLIGADA AND SPLETIVO.IDPERLET=STURMADISC.IDPERLET
	INNER JOIN SDISCIPLINA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SDISCIPLINA.CODCOLIGADA AND STURMADISC.CODDISC=SDISCIPLINA.CODDISC
	INNER JOIN SMATRICULA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SMATRICULA.IDTURMADISC
	INNER JOIN SSTATUS				(NOLOCK) ON SSTATUS.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SSTATUS.CODSTATUS=SMATRICULA.CODSTATUS
	INNER JOIN SMATRICPL			(NOLOCK) ON SMATRICPL.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SMATRICPL.RA=SMATRICULA.RA AND SMATRICPL.IDPERLET=SMATRICULA.IDPERLET 
												AND SMATRICPL.IDHABILITACAOFILIAL=SMATRICULA.IDHABILITACAOFILIAL
	INNER JOIN SFILIAL				(NOLOCK) ON SFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SFILIAL.CODFILIAL=SMATRICPL.CODFILIAL
	INNER JOIN GFILIAL				(NOLOCK) ON SFILIAL.CODCOLIGADA = GFILIAL.CODCOLIGADA AND SFILIAL.CODFILIAL=GFILIAL.CODFILIAL
	INNER JOIN SSTATUS STATUSLETIVO (NOLOCK) ON SMATRICPL.CODCOLIGADA = STATUSLETIVO.CODCOLIGADA AND SMATRICPL.CODSTATUS = STATUSLETIVO.CODSTATUS
	INNER JOIN SALUNO				(NOLOCK) ON SALUNO.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SALUNO.RA=SMATRICPL.RA
	INNER JOIN PPESSOA				(NOLOCK) ON PPESSOA.CODIGO=SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL	(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL=SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO				(NOLOCK) ON SCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STIPOCURSO			(NOLOCK) ON STIPOCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND STIPOCURSO.CODTIPOCURSO=SHABILITACAOFILIAL.CODTIPOCURSO



		WHERE ( STIPOCURSO.NOME LIKE 'GRAD%' AND STURMADISC.TIPO = 'P' )
		AND NOT (SMATRICULA.CODCOLIGADA = 3 AND SHABILITACAOFILIAL.CODTIPOCURSO = 1)
		AND STURMADISC.CODFILIAL != 4
		AND SPLETIVO.CODPERLET IN ('2023/1')
		AND (UPPER(SSTATUS.DESCRICAO) LIKE 'MATRIC%' )
		
	

	GROUP BY  STURMADISC.CODCOLIGADA,STURMADISC.CODFILIAL,GFILIAL.NOMEFANTASIA ,STIPOCURSO.CODTIPOCURSO,SCURSO.NOME,STIPOCURSO.NOME, SCURSO.CODCURSO,
	   SCURSO.NOME, SPLETIVO.CODPERLET,SDISCIPLINA.CODDISC,SDISCIPLINA.NOME, STURMADISC.IDTURMADISC,SALUNO.RA,PPESSOA.NOME,PPESSOA.EMAIL
											) AS X
										
										




--SELECT * FROM GFILIAL;
      


	 