SELECT DISTINCT GFILIAL.NOME AS NOMEFILIAL,SMATRICULA.RA,  STURMADISC.CODCOLIGADA,  STURMADISC.CODFILIAL,  STURMADISC.CODTIPOCURSO,  STURMADISC.ATIVA,  STURMADISC.IDHABILITACAOFILIAL,
  STURMADISC.IDTURMADISC,  STURMADISC.CODDISC,  STURMADISC.CODTURMA,  
  SDISCIPLINA.NOME AS NOMEDISCIPLINA,  SPLETIVO.CODPERLET, CASE WHEN STURNO.TIPO='M' THEN 'Matutino' 
																				WHEN STURNO.TIPO='V' THEN 'Vespertino'
																				WHEN STURNO.TIPO='I' THEN 'Semi-Integral' END  AS NOMETURNO,
  SCURSO.NOME AS NOMECURSO,SMATRICULA.RA,  SMATRICULA.NUMDIARIO,  PPESSOAALUNO.NOME AS NOMEALUNO,
  STIPOCURSO.APRESENTACAO, STIPOCURSO.NOME NIVEL
FROM STURMADISC (NOLOCK)   
 LEFT JOIN SPROFESSORTURMA (NOLOCK) ON (STURMADISC.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA AND STURMADISC.IDTURMADISC = SPROFESSORTURMA.IDTURMADISC)
 LEFT JOIN SPROFESSOR (NOLOCK) ON (SPROFESSORTURMA.CODCOLIGADA = SPROFESSOR.CODCOLIGADA AND SPROFESSORTURMA.CODPROF = SPROFESSOR.CODPROF)
 LEFT JOIN PPESSOA PPESSOAPROFESSOR(NOLOCK) ON (SPROFESSOR.CODPESSOA = PPESSOAPROFESSOR.CODIGO) 
 INNER JOIN SDISCIPLINA (NOLOCK) ON (STURMADISC.CODCOLIGADA = SDISCIPLINA.CODCOLIGADA AND STURMADISC.CODDISC = SDISCIPLINA.CODDISC)
 INNER JOIN SPLETIVO (NOLOCK) ON (STURMADISC.CODCOLIGADA = SPLETIVO.CODCOLIGADA AND STURMADISC.IDPERLET = SPLETIVO.IDPERLET)
 INNER JOIN GFILIAL (NOLOCK) ON (STURMADISC.CODCOLIGADA = GFILIAL.CODCOLIGADA AND STURMADISC.CODFILIAL = GFILIAL.CODFILIAL)
 LEFT JOIN SHABILITACAOFILIAL (NOLOCK) ON (STURMADISC.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND STURMADISC.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL)
 LEFT JOIN STURNO (NOLOCK) ON (SHABILITACAOFILIAL.CODCOLIGADA = STURNO.CODCOLIGADA AND SHABILITACAOFILIAL.CODTURNO = STURNO.CODTURNO)
 LEFT JOIN SCURSO (NOLOCK) ON (SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO)
 LEFT JOIN SHABILITACAO (NOLOCK) ON (SHABILITACAOFILIAL.CODCOLIGADA = SHABILITACAO.CODCOLIGADA AND SHABILITACAOFILIAL.CODCURSO = SHABILITACAO.CODCURSO
AND SHABILITACAOFILIAL.CODHABILITACAO = SHABILITACAO.CODHABILITACAO)
 INNER JOIN SMATRICULA (NOLOCK) ON (STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC)
 INNER JOIN SALUNO (NOLOCK) ON (SMATRICULA.CODCOLIGADA = SALUNO.CODCOLIGADA AND SMATRICULA.RA = SALUNO.RA)
 LEFT JOIN SMATRICPL (NOLOCK) ON (SMATRICPL.CODCOLIGADA=SALUNO.CODCOLIGADA AND SMATRICPL.RA=SALUNO.RA AND STURMADISC.CODTURMA=SMATRICPL.CODTURMA)
 INNER JOIN PPESSOA PPESSOAALUNO (NOLOCK) ON (SALUNO.CODPESSOA = PPESSOAALUNO.CODIGO)
 INNER JOIN SSTATUS (NOLOCK) ON (SMATRICULA.CODCOLIGADA = SSTATUS.CODCOLIGADA AND SMATRICULA.CODSTATUS = SSTATUS.CODSTATUS)
 INNER JOIN STIPOCURSO (NOLOCK) ON (STURMADISC.CODCOLIGADA  = STIPOCURSO.CODCOLIGADA AND STURMADISC.CODTIPOCURSO = STIPOCURSO.CODTIPOCURSO)
 INNER JOIN STURMA (NOLOCK) ON STURMADISC.CODCOLIGADA=STURMA.CODCOLIGADA AND STURMADISC.CODTURMA=STURMA.CODTURMA AND STURMADISC.IDPERLET=STURMA.IDPERLET


WHERE STURMADISC.CODCOLIGADA =1
AND STURMADISC.CODTIPOCURSO =1
AND STURMADISC.ATIVA = 'S'
AND SPLETIVO.ENCERRADO = 'N' 
AND STURMADISC.IDTURMADISC=124573
AND SSTATUS.PLDIARIO='S'

ORDER BY STURMADISC.CODCOLIGADA, STURMADISC.IDTURMADISC, SMATRICULA.NUMDIARIO