SELECT DISTINCT X.RA,X.IDMDL  FROM(	SELECT
			STURMADISC.CODCOLIGADA
			, STURMADISC.CODFILIAL
			, STURMADISC.CODTIPOCURSO
			, SCURSO.CODCURSO
			, CASE
				WHEN TURMAGERENCIAL.CODTURMA IS NULL THEN STURMADISC.CODTURMA
				ELSE TURMAGERENCIAL.CODTURMA
			  END CODTURMA
			, SMATRICULA.RA
			, STURMADISC.CODDISC
			, CASE
				WHEN TURMAGERENCIAL.IDTURMADISC IS NULL THEN STURMADISC.IDTURMADISC
				ELSE TURMAGERENCIAL.IDTURMADISC
			  END IDTURMADISC_MOODLE
			, STURMADISCCOMPL.IDMDL
			, STURMADISC.TIPO

		FROM STURMADISC (NOLOCK)
			INNER JOIN STURMADISCCOMPL				(NOLOCK) ON STURMADISC.CODCOLIGADA = STURMADISCCOMPL.CODCOLIGADA AND STURMADISC.IDTURMADISC = STURMADISCCOMPL.IDTURMADISC
			INNER JOIN SPLETIVO						(NOLOCK) ON STURMADISC.CODCOLIGADA = SPLETIVO.CODCOLIGADA AND STURMADISC.IDPERLET = SPLETIVO.IDPERLET
			INNER JOIN SMATRICULA					(NOLOCK) ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
			INNER JOIN SSTATUS						(NOLOCK) ON SMATRICULA.CODCOLIGADA = SSTATUS.CODCOLIGADA AND SSTATUS.CODSTATUS = SMATRICULA.CODSTATUS
			INNER JOIN ZMDSSTATUSSTATUSGLOBAL ZMDM	(NOLOCK) ON SSTATUS.CODCOLIGADA = ZMDM.CODCOLIGADA AND SSTATUS.CODSTATUS = ZMDM.CODSTATUS
			INNER JOIN SMATRICPL					(NOLOCK) ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET AND SMATRICULA.RA = SMATRICPL.RA
															AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
			INNER JOIN SHABILITACAOFILIAL			(NOLOCK) ON SMATRICPL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
			INNER JOIN SCURSO						(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
			LEFT  JOIN STURMADISCGERENCIADA			(NOLOCK) ON STURMADISCGERENCIADA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND STURMADISCGERENCIADA.IDTURMADISCGERENCIADA = STURMADISC.IDTURMADISC
			LEFT  JOIN STURMADISC TURMAGERENCIAL	(NOLOCK) ON TURMAGERENCIAL.CODCOLIGADA = STURMADISCGERENCIADA.CODCOLIGADA AND TURMAGERENCIAL.IDTURMADISC = STURMADISCGERENCIADA.IDTURMADISC 

		WHERE (SCURSO.CURPRESDIST = 'D' OR (SCURSO.CURPRESDIST <> 'D' AND STURMADISC.TIPO = 'D')) /*TRAZER OS ALUNOS 100% EAD E DA MODALIDADE PRESENCIAL E DISC EAD*/
		AND SPLETIVO.CODPERLET IN ('2022/2') /*PERIODO LETIVO*/
		AND STURMADISC.CODCOLIGADA IN (1,3,4)
		AND STURMADISCCOMPL.IDMDL IS NOT NULL
		AND STURMADISCCOMPL.IDMDL = 2
		AND ZMDM.IDSTATUSGLOBAL IN (1,2,3,6,8,12) /*MATRICULA, APROVADO, REPROVADO, REPROVADO POR FALTA, EXAME FINAL, TRANSFERENCIA DE CURSO*/ /*DISCIPLINA*/
	) AS X  