SELECT DISTINCT 
     X.CODCOLIGADA,
     CASE 
	   WHEN X.CODCOLIGADA = '1' THEN 'IME INSTITUTO METROPOLITANO DE ENSINO LTDA'  
	   WHEN X.CODCOLIGADA='3' THEN 'CENTRO DE ESTUDOS JURIDICOS DO AMAZONAS LTDA' END 'COLIGADA',
	   X.CODFILIAL,
	   X.NOMEFILIAL,
	   X.CODNIVEL,
	   X.NIVEL_ENSINO,
	   X.CODCURSO,
	   X.CURSO,
	   X.PERIODO,
	   X.CODDISC,
	   X.DISCIPLINA,
	   X.IDTURMA
	
FROM (SELECT STURMADISC.CODCOLIGADA CODCOLIGADA,
             STURMADISC.CODFILIAL CODFILIAL,
			 GFILIAL.NOMEFANTASIA NOMEFILIAL,
			 STIPOCURSO.CODTIPOCURSO CODNIVEL,
             STIPOCURSO.NOME NIVEL_ENSINO,
			 SCURSO.CODCURSO CODCURSO,
			 SCURSO.NOME CURSO,
			 SPLETIVO.CODPERLET PERIODO,
			 SDISCIPLINA.CODDISC CODDISC,
			 SDISCIPLINA.NOME DISCIPLINA,
			 STURMADISC.IDTURMADISC IDTURMA

FROM STURMADISC (NOLOCK)
	INNER JOIN SPLETIVO				(NOLOCK) ON STURMADISC.CODCOLIGADA=SPLETIVO.CODCOLIGADA AND SPLETIVO.IDPERLET=STURMADISC.IDPERLET
	INNER JOIN SDISCIPLINA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SDISCIPLINA.CODCOLIGADA AND STURMADISC.CODDISC=SDISCIPLINA.CODDISC
	INNER JOIN SMATRICULA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SMATRICULA.IDTURMADISC
	INNER JOIN SSTATUS				(NOLOCK) ON SSTATUS.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SSTATUS.CODSTATUS=SMATRICULA.CODSTATUS
	INNER JOIN SMATRICPL			(NOLOCK) ON SMATRICPL.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SMATRICPL.RA=SMATRICULA.RA AND SMATRICPL.IDPERLET=SMATRICULA.IDPERLET 
												AND SMATRICPL.IDHABILITACAOFILIAL=SMATRICULA.IDHABILITACAOFILIAL
	INNER JOIN SFILIAL				(NOLOCK) ON SFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SFILIAL.CODFILIAL=SMATRICPL.CODFILIAL
	INNER JOIN GFILIAL				(NOLOCK) ON SFILIAL.CODCOLIGADA = GFILIAL.CODCOLIGADA AND SFILIAL.CODFILIAL=GFILIAL.CODFILIAL
	INNER JOIN SSTATUS STATUSLETIVO (NOLOCK) ON SMATRICPL.CODCOLIGADA = STATUSLETIVO.CODCOLIGADA AND SMATRICPL.CODSTATUS = STATUSLETIVO.CODSTATUS
	INNER JOIN SALUNO				(NOLOCK) ON SALUNO.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SALUNO.RA=SMATRICPL.RA
	INNER JOIN PPESSOA				(NOLOCK) ON PPESSOA.CODIGO=SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL	(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL=SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO				(NOLOCK) ON SCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STIPOCURSO			(NOLOCK) ON STIPOCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND STIPOCURSO.CODTIPOCURSO=SHABILITACAOFILIAL.CODTIPOCURSO


WHERE (STURMADISC.CODCOLIGADA IN (1) OR (STURMADISC.CODCOLIGADA = 3 AND STURMADISC.CODTIPOCURSO = 3))
		AND SPLETIVO.CODPERLET='2022/2'
		AND STATUSLETIVO.DIINCALUNODISC = 'S'
		AND STIPOCURSO.NOME NOT LIKE 'EXTEN%'
		

	GROUP BY STURMADISC.CODCOLIGADA,STURMADISC.CODFILIAL,GFILIAL.NOMEFANTASIA ,STIPOCURSO.CODTIPOCURSO, SCURSO.NOME, STIPOCURSO.NOME,SCURSO.CODCURSO,
	SCURSO.NOME,SPLETIVO.CODPERLET,SDISCIPLINA.CODDISC,SDISCIPLINA.NOME, STURMADISC.IDTURMADISC
	
UNION

SELECT STURMADISC.CODCOLIGADA COLIGADA,
       STURMADISC.CODFILIAL CODFILIAL,
	   GFILIAL.NOMEFANTASIA NOMEFILIAL,
	   STIPOCURSO.CODTIPOCURSO CODNIVEL,
       STIPOCURSO.NOME NIVEL_ENSINO,
	   SCURSO.CODCURSO CODCURSO,
	   SCURSO.NOME CURSO,
	   SPLETIVO.CODPERLET PERIODO,
	   SDISCIPLINA.CODDISC CODDISC,
	   SDISCIPLINA.NOME DISCIPLINA,
	   STURMADISC.IDTURMADISC IDTURMA


FROM STURMADISC (NOLOCK)
	INNER JOIN SPLETIVO				(NOLOCK) ON STURMADISC.CODCOLIGADA=SPLETIVO.CODCOLIGADA AND SPLETIVO.IDPERLET=STURMADISC.IDPERLET
	INNER JOIN SDISCIPLINA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SDISCIPLINA.CODCOLIGADA AND STURMADISC.CODDISC=SDISCIPLINA.CODDISC
	INNER JOIN SMATRICULA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SMATRICULA.IDTURMADISC
	INNER JOIN SSTATUS				(NOLOCK) ON SSTATUS.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SSTATUS.CODSTATUS=SMATRICULA.CODSTATUS
	INNER JOIN SMATRICPL			(NOLOCK) ON SMATRICPL.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SMATRICPL.RA=SMATRICULA.RA AND SMATRICPL.IDPERLET=SMATRICULA.IDPERLET 
												AND SMATRICPL.IDHABILITACAOFILIAL=SMATRICULA.IDHABILITACAOFILIAL
	INNER JOIN SFILIAL				(NOLOCK) ON SFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SFILIAL.CODFILIAL=SMATRICPL.CODFILIAL
	INNER JOIN GFILIAL				(NOLOCK) ON SFILIAL.CODCOLIGADA = GFILIAL.CODCOLIGADA AND SFILIAL.CODFILIAL=GFILIAL.CODFILIAL
	INNER JOIN SSTATUS STATUSLETIVO (NOLOCK) ON SMATRICPL.CODCOLIGADA = STATUSLETIVO.CODCOLIGADA AND SMATRICPL.CODSTATUS = STATUSLETIVO.CODSTATUS
	INNER JOIN SALUNO				(NOLOCK) ON SALUNO.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SALUNO.RA=SMATRICPL.RA
	INNER JOIN PPESSOA				(NOLOCK) ON PPESSOA.CODIGO=SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL	(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL=SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO				(NOLOCK) ON SCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STIPOCURSO			(NOLOCK) ON STIPOCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND STIPOCURSO.CODTIPOCURSO=SHABILITACAOFILIAL.CODTIPOCURSO


WHERE (STURMADISC.CODCOLIGADA IN (1) OR (STURMADISC.CODCOLIGADA = 3 AND STURMADISC.CODTIPOCURSO = 3))
		AND SPLETIVO.CODPERLET='2022/2'
		AND STATUSLETIVO.DIINCALUNODISC = 'S'
		AND STIPOCURSO.NOME NOT LIKE 'EXTEN%'
	

	GROUP BY  STURMADISC.CODCOLIGADA,STURMADISC.CODFILIAL,GFILIAL.NOMEFANTASIA ,STIPOCURSO.CODTIPOCURSO,SCURSO.NOME,STIPOCURSO.NOME, SCURSO.CODCURSO,
	   SCURSO.NOME, SPLETIVO.CODPERLET,SDISCIPLINA.CODDISC,SDISCIPLINA.NOME, STURMADISC.IDTURMADISC
											) AS X 
											
	

	

	
	/*
	select * from sfilial

	select * from GLINKSREL where mastertable = 'sfilial'




	   if($resultdiscip == '{"exception":"moodle_exception","errorcode":"shortnametaken","message":"Nome breve j\u00e1 \u00e9 usado em um outro curso (0000001)"}' ){
        
            $msg[] = 'Todos os cursos cadastrados com sucesso';
            
            date_default_timezone_set('America/Manaus');

            $hoje ='atualizacao-'.date('d-m-Y H;i');

            $file = fopen('C:/Users/tiago.souza/Documents/GitHub/moodle-rm/app/Http/Controllers/logs-cursos/'.$hoje.'.txt','w');
            
            foreach ( $msg as $key => $value) {      
        
                fwrite($file, $value . PHP_EOL);

            }  
            fclose($file);

	*/