SELECT DISTINCT 
	X.RA AS USERNAME
	, 'student' AS ROLE1
	, '0' AS ENROLSTATUS1
	, X.NIVEL_ENSINO AS GROUP1
	, X.CURSO AS GROUP2
	, X.CODTURMA AS GROUP3
	, X.FILIAL AS GROUP4
	, X.NIVEL_ENSINO AS cohort1
	, X.CURSO AS cohort2
	, X.MODALIDADE AS cohort3
	, X.FILIAL AS cohort4
    , X.IDMDL

FROM(	SELECT
			STURMADISC.CODCOLIGADA
			, STURMADISC.CODFILIAL
			, STURMADISC.CODTIPOCURSO
			, SCURSO.CODCURSO
			, UPPER(SCURSO.NOME) CURSO
			, CASE
				WHEN TURMAGERENCIAL.CODTURMA IS NULL THEN STURMADISC.CODTURMA
				ELSE TURMAGERENCIAL.CODTURMA
			  END CODTURMA
			, SMATRICPL.RA
			, STURMADISC.CODDISC
			/*, CONCAT(STURMADISC.CODCOLIGADA,'-',CASE
													WHEN TURMAGERENCIAL.IDTURMADISC IS NULL THEN STURMADISC.IDTURMADISC
													ELSE TURMAGERENCIAL.IDTURMADISC END) COURSE1*/
			, 'ALUNO' AS PAPEL
			, SSTATUS.DESCRICAO STATUS_DISC
			, SS.DESCRICAO STATUS_PERIODO
			, GFILIAL.NOME FILIAL
			, REPLACE(REPLACE(STIPOCURSO.NOME,' - ','_'), ' ','_') NIVEL_ENSINO
			, CASE
				WHEN SCURSO.CURPRESDIST = 'P' AND STURMADISC.TIPO = 'D' THEN 'PRESENCIAL'
				WHEN SCURSO.CURPRESDIST = 'D' AND STURMADISC.TIPO = 'D' THEN 'EAD'
				WHEN SCURSO.CURPRESDIST = 'D' AND STURMADISC.TIPO = 'S' THEN 'SEMIPRESENCIAL'
			 END MODALIDADE
			, STURMADISCCOMPL.IDMDL AS IDMDL

		FROM STURMADISC (NOLOCK)
			INNER JOIN STURMADISCCOMPL			(NOLOCK) ON STURMADISC.CODCOLIGADA = STURMADISCCOMPL.CODCOLIGADA AND STURMADISC.IDTURMADISC = STURMADISCCOMPL.IDTURMADISC
			INNER JOIN SPLETIVO					(NOLOCK) ON STURMADISC.CODCOLIGADA = SPLETIVO.CODCOLIGADA AND STURMADISC.IDPERLET = SPLETIVO.IDPERLET
			INNER JOIN SMATRICULA				(NOLOCK) ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
			INNER JOIN SSTATUS					(NOLOCK) ON SMATRICULA.CODCOLIGADA = SSTATUS.CODCOLIGADA AND SMATRICULA.CODSTATUS = SSTATUS.CODSTATUS
			INNER JOIN ZMDSSTATUSSTATUSGLOBAL	(NOLOCK) ON SSTATUS.CODCOLIGADA = ZMDSSTATUSSTATUSGLOBAL.CODCOLIGADA AND SSTATUS.CODSTATUS = ZMDSSTATUSSTATUSGLOBAL.CODSTATUS
			INNER JOIN SMATRICPL				(NOLOCK) ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET AND SMATRICULA.RA = SMATRICPL.RA
														AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
			INNER JOIN SSTATUS SS				(NOLOCK) ON SMATRICPL.CODCOLIGADA = SS.CODCOLIGADA AND SMATRICPL.CODSTATUS = SS.CODSTATUS
			INNER JOIN SMOTIVOALTMAT (NOLOCK) ON SMOTIVOALTMAT.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			INNER JOIN ZMDSSTATUSSTATUSGLOBAL Z (NOLOCK) ON SS.CODCOLIGADA = Z.CODCOLIGADA AND SS.CODSTATUS = Z.CODSTATUS
			INNER JOIN SHABILITACAOFILIAL		(NOLOCK) ON SMATRICPL.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
			INNER JOIN SCURSO					(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
			LEFT JOIN STURMADISCGERENCIADA		(NOLOCK) ON STURMADISCGERENCIADA.CODCOLIGADA = STURMADISC.CODCOLIGADA AND STURMADISCGERENCIADA.IDTURMADISCGERENCIADA = STURMADISC.IDTURMADISC
			LEFT JOIN STURMADISC TURMAGERENCIAL (NOLOCK) ON TURMAGERENCIAL.CODCOLIGADA = STURMADISCGERENCIADA.CODCOLIGADA AND TURMAGERENCIAL.IDTURMADISC = STURMADISCGERENCIADA.IDTURMADISC 
			INNER JOIN STIPOCURSO				(NOLOCK) ON STURMADISC.CODCOLIGADA = STIPOCURSO.CODCOLIGADA AND STURMADISC.CODTIPOCURSO = STIPOCURSO.CODTIPOCURSO
			INNER JOIN GFILIAL					(NOLOCK) ON STURMADISC.CODCOLIGADA = GFILIAL.CODCOLIGADA AND STURMADISC.CODFILIAL = GFILIAL.CODFILIAL
			


		WHERE (SCURSO.CURPRESDIST = 'D' OR (SCURSO.CURPRESDIST = 'P' AND STURMADISC.TIPO = 'D')) /*TRAZER OS ALUNOS PRESENCIAIS PARA INCLUSÃO NO DIGITAL FAMETRO*/
		AND SPLETIVO.CODPERLET IN ('2022/2') /*PERIODO LETIVO*/
		AND NOT (SMATRICULA.CODCOLIGADA = 3 AND SHABILITACAOFILIAL.CODTIPOCURSO IN (1,12)) /*ALUNOS DA FST E FAMEC SÃO DE OUTRO AMBIENTE*/
		AND ZMDSSTATUSSTATUSGLOBAL.IDSTATUSGLOBAL IN (1) /*MATRICULADO*/ /*DISCIPLINA*/

		AND STURMADISCCOMPL.IDMDL IS NOT NULL


	) AS X 