SELECT DISTINCT 
	X.NIVEL_ENSINO
	, X.CURSO
	, X.CODTURMA TURMA
	, X.RA
	, X.ALUNO
	, X.CODDISC
	, X.NOME AS DISCIPLINA
	, X.TIPO_DISCIPLINA
	, X.PROFESSOR
	, X.CH
	, X.QTD_ALUNOS
	, X.N1
	, X.INSTI_N1
	, X.PARCIAL_N1
	, X.N2
	, X.INSTI_N2
	, X.PARCIAL_N2
	, X.QUANTIDADE
	, X.NOTA_ETAPA_N1 AS '1.NOTA_ETAPA_N1'
	, X.NOTA_INST_N1 '2.NOTA_INST_N1'
	, X.NOTA_PARCIAL_N1 '3.NOTA_PARCIAL_N1'
	, X.NOTA_ETAPA_N2 '4.NOTA_ETAPA_N2'
	, X.NOTA_INST_N2 '5.NOTA_INST_N2'
	, X.NOTA_PARCIAL_N2 '6.NOTA_PARCIAL_N2'
	, X.STATUS_DISC
	, X.STATUS_PERIODO

FROM (SELECT STIPOCURSO.NOME NIVEL_ENSINO
	, SCURSO.NOME CURSO
	, STURMADISC.CODTURMA
	, SALUNO.RA
	, PPESSOA.NOME ALUNO
	, STURMADISC.CODDISC
	, SDISCIPLINA.NOME
	, SDISCIPLINA.CH
	, P1.NOME AS PROFESSOR
	, COUNT(SMATRICULA.RA) QTD_ALUNOS
	, COUNT(N1.NOTAFALTA) N1
	, COUNT(INST.NOTA) INSTI_N1
	, COUNT(PARC.NOTA) PARCIAL_N1
	, COUNT(N2.NOTAFALTA) N2
	, COUNT(INSTN2.NOTA) INSTI_N2
	, COUNT(PARCN2.NOTA) PARCIAL_N2
	, 1 AS QUANTIDADE
	, N1.NOTAFALTA AS NOTA_ETAPA_N1
	, INST.NOTA AS NOTA_INST_N1
	, PARC.NOTA AS NOTA_PARCIAL_N1
	, N2.NOTAFALTA AS NOTA_ETAPA_N2
	, INSTN2.NOTA AS NOTA_INST_N2
	, PARCN2.NOTA AS NOTA_PARCIAL_N2
	, CASE
			WHEN STURMADISC.TIPO = 'P' THEN 'PRESENCIAL'
			WHEN STURMADISC.TIPO = 'S' THEN 'SEMIPRESENCIAL'
			WHEN STURMADISC.TIPO = 'D' THEN 'A DISTÂNCIA'
	  ELSE
			'NÃO ESPECIFICADO'
	  END 'TIPO_DISCIPLINA'
	, SSTATUS.DESCRICAO STATUS_DISC
	, STATUSLETIVO.DESCRICAO STATUS_PERIODO

FROM STURMADISC (NOLOCK)
	INNER JOIN SPLETIVO				(NOLOCK) ON STURMADISC.CODCOLIGADA=SPLETIVO.CODCOLIGADA AND SPLETIVO.IDPERLET=STURMADISC.IDPERLET
	INNER JOIN SDISCIPLINA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SDISCIPLINA.CODCOLIGADA AND STURMADISC.CODDISC=SDISCIPLINA.CODDISC
	INNER JOIN SMATRICULA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SMATRICULA.IDTURMADISC
	INNER JOIN SSTATUS				(NOLOCK) ON SSTATUS.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SSTATUS.CODSTATUS=SMATRICULA.CODSTATUS
	INNER JOIN SMATRICPL			(NOLOCK) ON SMATRICPL.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SMATRICPL.RA=SMATRICULA.RA AND SMATRICPL.IDPERLET=SMATRICULA.IDPERLET 
												AND SMATRICPL.IDHABILITACAOFILIAL=SMATRICULA.IDHABILITACAOFILIAL
	INNER JOIN SSTATUS STATUSLETIVO (NOLOCK) ON SMATRICPL.CODCOLIGADA = STATUSLETIVO.CODCOLIGADA AND SMATRICPL.CODSTATUS = STATUSLETIVO.CODSTATUS
	INNER JOIN SALUNO				(NOLOCK) ON SALUNO.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SALUNO.RA=SMATRICPL.RA
	INNER JOIN PPESSOA				(NOLOCK) ON PPESSOA.CODIGO=SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL	(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL=SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO				(NOLOCK) ON SCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STIPOCURSO			(NOLOCK) ON STIPOCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND STIPOCURSO.CODTIPOCURSO=SHABILITACAOFILIAL.CODTIPOCURSO
	INNER JOIN SETAPAS				(NOLOCK) ON STURMADISC.CODCOLIGADA=SETAPAS.CODCOLIGADA AND STURMADISC.IDTURMADISC=SETAPAS.IDTURMADISC AND SETAPAS.CODETAPA=1 AND SETAPAS.TIPOETAPA='F'
	/*Renan Arcanjo: Acrescimo do nome do professor da disciplina*/
	LEFT JOIN SPROFESSORTURMA		(NOLOCK) ON STURMADISC.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SPROFESSORTURMA.IDTURMADISC
	LEFT JOIN SPROFESSOR			(NOLOCK) ON SPROFESSORTURMA.CODCOLIGADA=SPROFESSOR.CODCOLIGADA AND SPROFESSORTURMA.CODPROF = SPROFESSOR.CODPROF
	LEFT JOIN PPESSOA P1			(NOLOCK) ON SPROFESSOR.CODPESSOA = P1.CODIGO
	
	LEFT JOIN SNOTAETAPA N1			(NOLOCK) ON N1.CODCOLIGADA=STURMADISC.CODCOLIGADA AND N1.IDTURMADISC=STURMADISC.IDTURMADISC AND N1.CODETAPA=1 AND N1.TIPOETAPA='N' 
										AND SMATRICULA.RA = N1.RA AND N1.NOTAFALTA IS NOT NULL
	LEFT JOIN SNOTAS INST			(NOLOCK) ON INST.CODCOLIGADA=STURMADISC.CODCOLIGADA AND INST.IDTURMADISC=STURMADISC.IDTURMADISC AND INST.CODETAPA=1 AND INST.CODPROVA = 1 
										AND INST.TIPOETAPA='N' AND SMATRICULA.RA=INST.RA
	LEFT JOIN SNOTAS PARC			(NOLOCK) ON PARC.CODCOLIGADA=STURMADISC.CODCOLIGADA AND PARC.IDTURMADISC=STURMADISC.IDTURMADISC AND PARC.CODETAPA=1 AND PARC.CODPROVA = 2 
										AND PARC.TIPOETAPA='N' AND SMATRICULA.RA=PARC.RA 
	LEFT JOIN SNOTAETAPA N2			(NOLOCK) ON N2.CODCOLIGADA=STURMADISC.CODCOLIGADA AND N2.IDTURMADISC=STURMADISC.IDTURMADISC AND N2.CODETAPA=2 AND N2.TIPOETAPA='N' 
										AND SMATRICULA.RA = N2.RA AND N2.NOTAFALTA IS NOT NULL
	LEFT JOIN SNOTAS INSTN2			(NOLOCK) ON INSTN2.CODCOLIGADA=STURMADISC.CODCOLIGADA AND INSTN2.IDTURMADISC=STURMADISC.IDTURMADISC AND INSTN2.CODETAPA=2 
										AND INSTN2.CODPROVA = 1 AND INSTN2.TIPOETAPA='N' AND SMATRICULA.RA=INSTN2.RA
	LEFT JOIN SNOTAS PARCN2			(NOLOCK) ON PARCN2.CODCOLIGADA=STURMADISC.CODCOLIGADA AND PARCN2.IDTURMADISC=STURMADISC.IDTURMADISC AND PARCN2.CODETAPA=2 
										AND PARCN2.CODPROVA = 2 AND PARCN2.TIPOETAPA='N' AND SMATRICULA.RA=PARCN2.RA

WHERE (STURMADISC.CODCOLIGADA IN (1,4) OR (STURMADISC.CODCOLIGADA = 3 AND STURMADISC.CODTIPOCURSO = 3))
		AND SPLETIVO.CODPERLET='2023/1'
		AND STATUSLETIVO.DIINCALUNODISC = 'S'
		AND STIPOCURSO.NOME NOT LIKE 'EXTEN%'
		

	GROUP BY SCURSO.NOME, STIPOCURSO.NOME, STURMADISC.CODTURMA, SALUNO.RA, PPESSOA.NOME, STURMADISC.CODDISC, P1.NOME, SDISCIPLINA.NOME, SDISCIPLINA.CH, SETAPAS.AULASDADAS,
	N1.NOTAFALTA , INST.NOTA , PARC.NOTA ,N2.NOTAFALTA , INSTN2.NOTA , PARCN2.NOTA , STURMADISC.TIPO, SSTATUS.DESCRICAO, STATUSLETIVO.DESCRICAO
	
UNION

SELECT STIPOCURSO.NOME NIVEL_ENSINO
	, SCURSO.NOME CURSO
	, STURMADISC.CODTURMA
	, SALUNO.RA
	, PPESSOA.NOME ALUNO
	, STURMADISC.CODDISC
	, SDISCIPLINA.NOME
	, SDISCIPLINA.CH
	, P1.NOME AS PROFESSOR
	, COUNT(SMATRICULA.RA) QTD_ALUNOS
	, COUNT(N1.NOTAFALTA) N1
	, COUNT(INST.NOTA) INSTI_N1
	, COUNT(PARC.NOTA) PARCIAL_N1
	, COUNT(N2.NOTAFALTA) N2
	, COUNT(INSTN2.NOTA) INSTI_N2
	, COUNT(PARCN2.NOTA) PARCIAL_N2
	, 1 AS QUANTIDADE
	, N1.NOTAFALTA AS NOTA_ETAPA_N1
	, INST.NOTA AS NOTA_INST_N1
	, PARC.NOTA AS NOTA_PARCIAL_N1
	, N2.NOTAFALTA AS NOTA_ETAPA_N2
	, INSTN2.NOTA AS NOTA_INST_N2
	, PARCN2.NOTA AS NOTA_PARCIAL_N2
	, CASE
			WHEN STURMADISC.TIPO = 'P' THEN 'PRESENCIAL'
			WHEN STURMADISC.TIPO = 'S' THEN 'SEMIPRESENCIAL'
			WHEN STURMADISC.TIPO = 'D' THEN 'A DISTÂNCIA'
	  ELSE
			'NÃO ESPECIFICADO'
	  END 'TIPO_DISCIPLINA'
	, SSTATUS.DESCRICAO STATUS_DISC
	, STATUSLETIVO.DESCRICAO STATUS_PERIODO

FROM STURMADISC (NOLOCK)
	INNER JOIN SPLETIVO				(NOLOCK) ON STURMADISC.CODCOLIGADA=SPLETIVO.CODCOLIGADA AND SPLETIVO.IDPERLET=STURMADISC.IDPERLET
	INNER JOIN SDISCIPLINA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SDISCIPLINA.CODCOLIGADA AND STURMADISC.CODDISC=SDISCIPLINA.CODDISC
	INNER JOIN SMATRICULA			(NOLOCK) ON STURMADISC.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SMATRICULA.IDTURMADISC
	INNER JOIN SSTATUS				(NOLOCK) ON SSTATUS.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SSTATUS.CODSTATUS=SMATRICULA.CODSTATUS
	INNER JOIN SMATRICPL			(NOLOCK) ON SMATRICPL.CODCOLIGADA=SMATRICULA.CODCOLIGADA AND SMATRICPL.RA=SMATRICULA.RA AND SMATRICPL.IDPERLET=SMATRICULA.IDPERLET 
												AND SMATRICPL.IDHABILITACAOFILIAL=SMATRICULA.IDHABILITACAOFILIAL
	INNER JOIN SSTATUS STATUSLETIVO (NOLOCK) ON SMATRICPL.CODCOLIGADA = STATUSLETIVO.CODCOLIGADA AND SMATRICPL.CODSTATUS = STATUSLETIVO.CODSTATUS
	INNER JOIN SALUNO				(NOLOCK) ON SALUNO.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SALUNO.RA=SMATRICPL.RA
	INNER JOIN PPESSOA				(NOLOCK) ON PPESSOA.CODIGO=SALUNO.CODPESSOA
	INNER JOIN SHABILITACAOFILIAL	(NOLOCK) ON SHABILITACAOFILIAL.CODCOLIGADA=SMATRICPL.CODCOLIGADA AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL=SMATRICPL.IDHABILITACAOFILIAL
	INNER JOIN SCURSO				(NOLOCK) ON SCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND SCURSO.CODCURSO=SHABILITACAOFILIAL.CODCURSO
	INNER JOIN STIPOCURSO			(NOLOCK) ON STIPOCURSO.CODCOLIGADA=SHABILITACAOFILIAL.CODCOLIGADA AND STIPOCURSO.CODTIPOCURSO=SHABILITACAOFILIAL.CODTIPOCURSO
	INNER JOIN SETAPAS				(NOLOCK) ON STURMADISC.CODCOLIGADA=SETAPAS.CODCOLIGADA AND STURMADISC.IDTURMADISC=SETAPAS.IDTURMADISC AND SETAPAS.CODETAPA=2 AND SETAPAS.TIPOETAPA='F'
	/*Renan Arcanjo: Acrescimo do nome do professor da disciplina*/
	LEFT JOIN SPROFESSORTURMA		(NOLOCK) ON STURMADISC.CODCOLIGADA = SPROFESSORTURMA.CODCOLIGADA AND STURMADISC.IDTURMADISC=SPROFESSORTURMA.IDTURMADISC
	LEFT JOIN SPROFESSOR			(NOLOCK) ON SPROFESSORTURMA.CODCOLIGADA=SPROFESSOR.CODCOLIGADA AND SPROFESSORTURMA.CODPROF = SPROFESSOR.CODPROF
	LEFT JOIN PPESSOA P1			(NOLOCK) ON SPROFESSOR.CODPESSOA = P1.CODIGO
	
	LEFT JOIN SNOTAETAPA N1			(NOLOCK) ON N1.CODCOLIGADA=STURMADISC.CODCOLIGADA AND N1.IDTURMADISC=STURMADISC.IDTURMADISC AND N1.CODETAPA=1 AND N1.TIPOETAPA='N' 
										AND SMATRICULA.RA = N1.RA AND N1.NOTAFALTA IS NOT NULL
	LEFT JOIN SNOTAS INST			(NOLOCK) ON INST.CODCOLIGADA=STURMADISC.CODCOLIGADA AND INST.IDTURMADISC=STURMADISC.IDTURMADISC AND INST.CODETAPA=1 AND INST.CODPROVA = 1 
										AND INST.TIPOETAPA='N' AND SMATRICULA.RA=INST.RA
	LEFT JOIN SNOTAS PARC			(NOLOCK) ON PARC.CODCOLIGADA=STURMADISC.CODCOLIGADA AND PARC.IDTURMADISC=STURMADISC.IDTURMADISC AND PARC.CODETAPA=1 AND PARC.CODPROVA = 2 
										AND PARC.TIPOETAPA='N' AND SMATRICULA.RA=PARC.RA 
	LEFT JOIN SNOTAETAPA N2			(NOLOCK) ON N2.CODCOLIGADA=STURMADISC.CODCOLIGADA AND N2.IDTURMADISC=STURMADISC.IDTURMADISC AND N2.CODETAPA=2 AND N2.TIPOETAPA='N' 
										AND SMATRICULA.RA = N2.RA AND N2.NOTAFALTA IS NOT NULL
	LEFT JOIN SNOTAS INSTN2			(NOLOCK) ON INSTN2.CODCOLIGADA=STURMADISC.CODCOLIGADA AND INSTN2.IDTURMADISC=STURMADISC.IDTURMADISC AND INSTN2.CODETAPA=2 
										AND INSTN2.CODPROVA = 1 AND INSTN2.TIPOETAPA='N' AND SMATRICULA.RA=INSTN2.RA
	LEFT JOIN SNOTAS PARCN2			(NOLOCK) ON PARCN2.CODCOLIGADA=STURMADISC.CODCOLIGADA AND PARCN2.IDTURMADISC=STURMADISC.IDTURMADISC AND PARCN2.CODETAPA=2 
										AND PARCN2.CODPROVA = 2 AND PARCN2.TIPOETAPA='N' AND SMATRICULA.RA=PARCN2.RA

WHERE (STURMADISC.CODCOLIGADA IN (1) OR (STURMADISC.CODCOLIGADA = 3 AND STURMADISC.CODTIPOCURSO = 3))
		AND SPLETIVO.CODPERLET='2023/1'
		AND STATUSLETIVO.DIINCALUNODISC = 'S'
		AND STIPOCURSO.NOME NOT LIKE 'EXTEN%'
	

	GROUP BY SCURSO.NOME, STIPOCURSO.NOME, STURMADISC.CODTURMA, SALUNO.RA, PPESSOA.NOME, STURMADISC.CODDISC, SDISCIPLINA.NOME, SDISCIPLINA.CH, SETAPAS.AULASDADAS,
	N1.NOTAFALTA , INST.NOTA , PARC.NOTA ,N2.NOTAFALTA , INSTN2.NOTA , PARCN2.NOTA, P1.NOME, STURMADISC.TIPO, SSTATUS.DESCRICAO, STATUSLETIVO.DESCRICAO
											) AS X 
											/*WHERE X.RA = 2029249*/
	

	ORDER BY 1,2,3,7,9
